/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Exercicio2GUI;

import java.awt.Font;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;


public class Radio extends javax.swing.JFrame {
    
    private Font Fnormal, Fnegrito, Fitalico, FnegritoItalico;
    public Radio() {
        initComponents();
        Fnormal = new Font("Arial", Font.PLAIN, 14);
        Fnegrito = new Font("Arial", Font.BOLD, 14);
        Fitalico = new Font("Arial", Font.ITALIC, 14);
        FnegritoItalico = new Font("Arial", Font.BOLD | Font.ITALIC, 14);
        
        RadioButtonHandler rbh = new RadioButtonHandler();
        rbNormal.addItemListener(rbh);
        rbNegrito.addItemListener(rbh);
        rbItalico.addItemListener(rbh);
        rbNegritoItalico.addItemListener(rbh);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbBotoes = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtTexto = new javax.swing.JTextField();
        rbNormal = new javax.swing.JRadioButton();
        rbNegrito = new javax.swing.JRadioButton();
        rbItalico = new javax.swing.JRadioButton();
        rbNegritoItalico = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Texto");

        txtTexto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTexto.setText("Digite um texto");

        gbBotoes.add(rbNormal);
        rbNormal.setSelected(true);
        rbNormal.setText("Normal");
        rbNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNormalActionPerformed(evt);
            }
        });

        gbBotoes.add(rbNegrito);
        rbNegrito.setText("Negrito");

        gbBotoes.add(rbItalico);
        rbItalico.setText("Itálico");

        gbBotoes.add(rbNegritoItalico);
        rbNegritoItalico.setText("Negrito e Itálico");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbItalico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbNegritoItalico))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbNormal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbNegrito))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbNormal)
                    .addComponent(rbNegrito))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbItalico)
                    .addComponent(rbNegritoItalico))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNormalActionPerformed

    private class RadioButtonHandler implements ItemListener {

        public void itemStateChanged(ItemEvent e) {
            if(e.getSource() == rbNegrito) {
                txtTexto.setFont(Fnegrito);
            }
            if(e.getSource() == rbItalico) {
                txtTexto.setFont(Fitalico);
            }
            if(e.getSource() == rbNegritoItalico) {
                txtTexto.setFont(FnegritoItalico);
            }
            if(e.getSource() == rbNormal) {
                txtTexto.setFont(Fnormal);
            }
            
            txtTexto.repaint();

        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Radio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Radio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Radio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Radio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Radio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup gbBotoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbItalico;
    private javax.swing.JRadioButton rbNegrito;
    private javax.swing.JRadioButton rbNegritoItalico;
    private javax.swing.JRadioButton rbNormal;
    private javax.swing.JTextField txtTexto;
    // End of variables declaration//GEN-END:variables
}
